### ISSUE TITLE
openJDK 17 - Alpine

### ISSUE THREAD

**Issue by ryantheleach** [docker-library/oi-janky-groovy#18]
Apologies if this is the wrong place, but I was having troubles finding the right place.

https://hub.docker.com/layers/openjdk/library/openjdk/17-alpine/images/sha256-a996cdcc040704ec6badaf5fecf1e144c096e00231a29188596c784bcf858d05?context=explore

Appears to be running an outdated version of Java 17, which is having an effect on consumers.

https://openjdk.java.net/projects/jdk/17/ lists openJDK 17 reaching General Availability on 2021/09/14

But the image linked hasn't been updated in 6 months, and is running an early access version, missing parts of the final JRE 17.

This is likely to have a very large ripple effect in the coming months, for running Minecraft 1.18.1 on alpine images, which is popular among Minecraft Hosting Networks.

Again apologies if this isn't the right method of contact, there appeared to be no apt way to contact a publisher of a docker tag/image.

**Comment by wglambert** [comment]
Alpine is only available on early-access releases, once it reaches GA Alpine goes away

See https://github.com/docker-library/openjdk/issues/272

**Comment by ryantheleach** [comment]
Thanks for the help!

**Comment by yosifkit** [comment]
It is on the [Docker Hub description](https://hub.docker.com/_/openjdk) ([src](https://github.com/docker-library/docs/tree/8c6192fc11e6a4e2ce13148ba387cc820330aaea/openjdk#openjdkversion-alpine)):

> ## `openjdk:<version>-alpine`
>
> This image is based on the popular [Alpine Linux project](https://alpinelinux.org), available in [the `alpine` official image](https://hub.docker.com/_/alpine). Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.
>
>The OpenJDK port for Alpine is not in a supported release by OpenJDK, since it is not in the mainline code base. It is only available as early access builds of [OpenJDK Project Portola](http://openjdk.java.net/projects/portola). See also [this comment](https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754). So this image follows what is available from the OpenJDK project's maintainers.
>
>What this means is that Alpine based images are only released for early access release versions of OpenJDK. Once a particular release becomes a "General-Availability" release, the Alpine version is dropped from the "Supported Tags"; they are still available to pull, but will no longer be updated.
