### ISSUE TITLE
Persistent builds given uncoupled tags for multiarch pipeline?

### ISSUE THREAD

**Issue by ruffsl** [docker-library/oi-janky-groovy#3]
Again, forgive me if this isn't the place for it, but I was curious as to why one tag failure for an official build should prevent consecutive builds of uncoupled tags? I just noticed that an upstream issue with trusty is preventing our nested set of unrelated tags with a base image from xenial from even attempting to build:

https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/ros/1/console

If I understand correctly, the pipeline is pulling down all necessary parent images from the registry, then attempting to `bashbrew build <repo>` with a max retry count of 3, then gives up. I'm not completely familiar with the entire pipeline, but is this the section of bashbew setup and build:

https://github.com/docker-library/oi-janky-groovy/blob/954cc16f7adef051f530d9bd012fe79b71d972e3/update.sh/target-pipeline.groovy#L164-L167

It's not a huge deal, as presumably all tags within an official image should be stable and building eventually, however I don't feel like a build issue with one set of tags should prevent another set of uncoupled tags, within the same multiarch job, from pushing newer images, like with security updates and what not.

I suppose this has more to do with how to carefully convey the tag hierarchy onto the build pipeline for concurrency, but it would be a nice feature to have. Perhaps this would require breaking up uncoupled tags into separate jobs so that ill defined partial builds could be avoided?

**Comment by tianon** [comment]
This was fixed in https://github.com/docker-library/oi-janky-groovy/commit/3cb446d944bbbcb89b8cb7389db4b8f34274434b#diff-aaeafef566e8e81c52187f88fe813f5b (and some of the subsequent commits). :+1:

(Now a failing build will mark the build as "unstable" and it'll only be outright failed if _all_ tags fail to build.)
