### ISSUE TITLE
Publish ARM version of `7.6-jdk17-alpine`

### ISSUE THREAD

**Issue by SamTheisens** [docker-library/oi-janky-groovy#39]
Hi 👋 
I noticed that there aren't any ARM builds for [7.6-jdk17-alpine](https://hub.docker.com/_/gradle/tags?page=&page_size=&ordering=&name=7.6-jdk17-alpine), while there are for all the other [distributions](https://hub.docker.com/_/gradle/tags?page=&page_size=&ordering=&name=7.6-jdk17) you publish.
Any chance this could be done? Would be happy to help, but would need some pointers 🙏 .

**Comment by LaurentGoderre** [comment]
This is the wrong repo for this question. Please open an issue at https://github.com/keeganwitt/docker-gradle. It seems that the alpine variants are limited to amd64.

**Comment by SamTheisens** [comment]
Submitted the issue there https://github.com/keeganwitt/docker-gradle/issues/292. Thanks.
